/**
 * Import COMET masks and NIMBUS predictions into QuPath.
 *
 * This script is intended for the final QuPath-side step of the COMET workflow.
 * It takes the per-FOV mask outputs from the Cellpose-based segmentation stage together
 * with the per-cell prediction values generated by NIMBUS, then reconstructs the detections
 * on the whole-slide image inside QuPath.
 *
 * Tested with QuPath v0.5.x and intended to remain compatible with QuPath v0.6.0.
 *
 * The script will:
 * 1. Read field-of-view coordinates from `fov_coordinates.csv`
 * 2. Read per-cell prediction or measurement values from `nimbus_cell_table.csv`
 * 3. Import one label mask per FOV at the corresponding whole-slide location
 * 4. Copy the NIMBUS-derived values to the imported detections as QuPath measurements
 *
 * Expected inputs:
 * - A whole-slide image open in QuPath
 * - One mask file per FOV in the configured mask directory
 * - Matching FOV identifiers across the coordinate CSV, measurement CSV, and mask filenames
 * - Matching label identifiers between each mask and the `label` column in the measurement CSV
 *
 * In a standard COMET output directory, these files are typically:
 * - `fov_coordinates.csv`
 * - `segmentation/deepcell_output/<FOV_name>_whole_cell.tiff`
 * - `nimbus_output/nimbus_cell_table.csv`
 *
 * Update the paths in the configuration section before running the script.
 *
 * @author Jiaqi Yang
 */

// Required imports
import qupath.lib.analysis.images.ContourTracing
import qupath.lib.io.TMAScoreImporter
import qupath.lib.regions.RegionRequest
import java.io.File // Required by TMAScoreImporter.readCSV(new File(...))

// Configuration: update these paths for your own COMET output directory before running the script

// Example COMET slide directory
def slideDir = "/path/to/my_experiment/Slide1"

// Full path to the FOV coordinate table (`fov_coordinates.csv`)
def csvPathCoords = "${slideDir}/fov_coordinates.csv"

// Full path to the per-cell measurement table (`nimbus_cell_table.csv`)
def csvPathMeasurements = "${slideDir}/nimbus_output/nimbus_cell_table.csv"

// Directory containing the exported whole-cell mask files
def maskDir = "${slideDir}/segmentation/deepcell_output"

// File suffix appended to each FOV name when locating the corresponding mask
def maskSuffix = "_whole_cell.tiff"


// Load the NIMBUS table first so values can be assigned immediately after mask import
print "[1/4] Loading NIMBUS table: nimbus_cell_table.csv"

def allFovData = [:] // Main lookup table: Map<FOV_Name, Map<Label, RowMap>>
def csvDataMeasurements
try {
    csvDataMeasurements = TMAScoreImporter.readCSV(new File(csvPathMeasurements))
} catch (Exception e) {
    print "[ERROR] Failed to read the measurement CSV: " + e.message
    return
}

// Extract the key identifier columns from the measurement table
def fovList = csvDataMeasurements.get('fov')
def labelList = csvDataMeasurements.get('label')
if (fovList == null || labelList == null) {
    print "[ERROR] The measurement CSV must contain 'fov' and 'label' columns."
    return
}
// Treat all remaining columns as NIMBUS-derived prediction or phenotype columns
def markerColumns = csvDataMeasurements.keySet().findAll { it != 'fov' && it != 'label' }
print "[INFO] Found ${markerColumns.size()} marker columns: ${markerColumns}"

// Build a nested lookup table for fast access during mask import
for (int i = 0; i < fovList.size(); i++) {
    def fov = fovList.get(i).toString()
    def label = labelList.get(i).toString() // Label identifier from the CSV, e.g. "10875"
    
    // Collect all measurement values for the current cell
    def rowMap = [:]
    markerColumns.each { markerName ->
        def value = csvDataMeasurements.get(markerName).get(i)
        rowMap.put(markerName, value)
    }
    
    // Store the row in the per-FOV lookup table
    if (!allFovData.containsKey(fov)) {
        allFovData[fov] = [:] // Create the inner map when this FOV is seen for the first time
    }
    allFovData[fov][label] = rowMap
}
print "[1/4] Loaded measurement data for ${allFovData.size()} FOVs."


// Load the coordinate table used to place each FOV mask on the whole-slide image
print "[2/4] Loading FOV coordinates: fov_coordinates.csv"
def csvDataCoords
try {
    csvDataCoords = TMAScoreImporter.readCSV(new File(csvPathCoords))
} catch (Exception e) {
    print "[ERROR] Failed to read the coordinate CSV: " + e.message
    return
}

// Extract the required coordinate columns
def fovNameList = csvDataCoords.get('FOV_Name')
def xList = csvDataCoords.get('X')
def yList = csvDataCoords.get('Y')
def wList = csvDataCoords.get('Width')
def hList = csvDataCoords.get('Height')

if (fovNameList == null || xList == null || yList == null || wList == null || hList == null) {
    print "[ERROR] The coordinate CSV must contain 'FOV_Name', 'X', 'Y', 'W', and 'H' columns."
    return
}
print "[2/4] Loaded coordinates for ${fovNameList.size()} FOVs."


// Import each mask, convert labels to detections, and attach the corresponding NIMBUS values
print "[3/4] Importing masks and attaching NIMBUS measurements"
def imageData = getCurrentImageData()
if (imageData == null) {
    print "[ERROR] Please open a whole-slide image in QuPath before running this script."
    return
}
def hierarchy = imageData.getHierarchy()
def server = imageData.getServer()
def serverPath = server.getPath() // Needed to create the RegionRequest for each FOV

int importedFovCount = 0
int notFoundFovCount = 0
int totalObjectsImported = 0
int totalMeasurementsMerged = 0

// Iterate over the coordinate table, since this defines where each FOV belongs on the slide
for (int i = 0; i < fovNameList.size(); i++) {
    
    // Read the placement information for the current FOV
    def fovName = fovNameList.get(i).toString() // Example: "fov0"
    def x, y, w, h
    try {
        x = xList.get(i).toString().toInteger()
        y = yList.get(i).toString().toInteger()
        w = wList.get(i).toString().toInteger()
        h = hList.get(i).toString().toInteger()
    } catch (NumberFormatException e) {
        print "[WARN] Skipping ${fovName} because one or more coordinates are not valid integers."
        continue
    }

    // Resolve the expected mask filename for this FOV
    File maskFile = new File(maskDir, fovName + maskSuffix)

    if (maskFile.exists()) {
        print "[INFO] Processing ${fovName}"
        try {
            // Import the label mask and map it into whole-slide coordinates
            def region = RegionRequest.createInstance(serverPath, 1.0, x, y, w, h)
            def detections = ContourTracing.labelsToDetections(maskFile.toPath(), region)
            
            // Get the NIMBUS rows associated with this FOV
            def measurementMap = allFovData.get(fovName)
            int mergeCount = 0
            
            if (measurementMap != null) {
                // Match each imported detection by label and copy over all numeric measurements
                detections.each { detection ->
                    def detLabel = detection.getName() // Label identifier recovered from the mask
                    def rowMap = measurementMap.get(detLabel)
                    
                    if (rowMap != null) {
                        def measurements = detection.getMeasurementList()
                        rowMap.keySet().each { colName ->
                            try {
                                // QuPath measurements must be numeric, so non-numeric values are skipped
                                def numValue = Double.parseDouble(rowMap.get(colName).toString())
                                measurements.put(colName, numValue)
                            } catch (NumberFormatException e) {
                                // Ignore values that cannot be converted to numbers
                            }
                        }
                        mergeCount++
                    }
                }
            } else {
                print "[WARN] No measurement rows were found for ${fovName} in nimbus_cell_table.csv."
            }
            
            // Add the imported detections to the current image hierarchy
            hierarchy.addObjects(detections)
            
            print "[INFO] Imported ${detections.size()} detections and merged measurements for ${mergeCount} labels in ${fovName}."
            importedFovCount++
            totalObjectsImported += detections.size()
            totalMeasurementsMerged += mergeCount

        } catch (Exception e) {
            print "[ERROR] Failed while importing ${fovName}: " + e.message
            e.printStackTrace()
        }

    } else {
        print "[WARN] Mask file not found for ${fovName}."
        print "[INFO] Expected path: " + maskFile.getAbsolutePath()
        notFoundFovCount++
    }
}

// Refresh QuPath and report a short summary
fireHierarchyUpdate()
print "[4/4] Import complete."
print "[SUMMARY] Imported ${importedFovCount} FOVs."
print "[SUMMARY] Created ${totalObjectsImported} cell detections."
print "[SUMMARY] Merged measurements for ${totalMeasurementsMerged} labels."
if (notFoundFovCount > 0) {
    print "[SUMMARY] ${notFoundFovCount} mask files were not found. Check the configured slide directory and mask suffix."
}
